version: '3'

services:
    rundeck:
        build: 
          context: ./
          args:
            RUNDECK_IMAGE: rundeck/rundeck:4.6.0
        environment:
            RUNDECK_DATABASE_DRIVER: oracle.jdbc.driver.OracleDriver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:oracle:thin:@oracle:1521:xe
            RUNDECK_DATABASE_DIALECT: org.rundeck.hibernate.RundeckOracleDialect
        volumes:
          - ./lib:/home/rundeck/server/lib
        ports:
          - 4440:4440
    oracle:
        image: oracleinanutshell/oracle-xe-11g:latest
        expose:
          - 1521
